language: python
before_install:
    - pip3 install --only-binary=scipy,numpy numpy scipy
    - pip3 install coveralls
python:
    - 3.5
    - 3.6
install: 
    - pip3 install --prefix=~/.local .
script: 
    - coverage run --source=numericalmodel --omit=numericalmodel/gui.py setup.py test
after_success:
    - coveralls
